### ISSUE TITLE
itertool.map has no length

### ISSUE THREAD

**Issue by shizhaoLiu0207** [slinderman/pyhsmm_spiketrains#1]
Line 33 "N_used = len(true_hmm.used_states)". "true_hmm.used_states" is itermap.tool type and has no length....

I am not sure if this is because Python version. I'm using Python 2.7.6. What version are you using?

**Comment by slinderman** [comment]
Thanks.  This was a regression in `pyhsmm`.  I've fixed it in https://github.com/mattjj/pyhsmm/commit/83f0bf1e3798c3625b7fee2d25b4b8a52f0a99e7.  Please pull the latest `pyhsmm` from master and then try running the `pyhsmm_spiketrains` demo.  It is working for me with python 2.7.13.
